name: CI

on:
  push:
    branches: [ main, develop, init ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
      max-parallel: 2

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest test_claude_api.py -v
      env:
        ANTHROPIC_API_KEY: test-key-for-ci

    - name: Run syntax check
      run: |
        python -m py_compile claude_api.py
        python -m py_compile test_claude_api.py

  quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install quality tools
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black

    - name: Run flake8
      run: |
        flake8 claude_api.py test_claude_api.py --max-line-length=100 --ignore=E203,W503 || true

    - name: Check code formatting with black
      run: |
        black --check claude_api.py test_claude_api.py --line-length=100 || true